import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database with Dutch defaults...')

  // Create default Dutch invoice template
  const nlTemplate = await prisma.invoiceTemplate.upsert({
    where: { id: 'default-nl' },
    update: {},
    create: {
      id: 'default-nl',
      name: 'Professioneel Nederlands',
      description: 'Standaard Nederlandse professionele factuur',
      language: 'nl',
      currency: 'EUR',
      currencySymbol: '€',
      currencyPosition: 'before',
      isDefault: true,
      labels: JSON.stringify({
        invoice: 'FACTUUR',
        invoiceNumber: 'Factuurnummer',
        date: 'Factuurdatum',
        dueDate: 'Vervaldatum',
        description: 'Omschrijving',
        quantity: 'Aantal',
        unitPrice: 'Eenheidsprijs',
        amount: 'Bedrag',
        subtotal: 'Subtotaal',
        tax: 'BTW',
        total: 'Totaal',
        paymentInfo: 'Betalingsgegevens',
        paymentTerms: 'Betalingsvoorwaarden',
        bankAccount: 'Bankrekening',
        iban: 'IBAN',
        bic: 'BIC',
        vatNumber: 'BTW-nummer',
        kvkNumber: 'KVK-nummer',
        from: 'Van',
        to: 'Aan',
        thankYou: 'Bedankt voor uw opdracht!',
        dueIn: 'Vervalt over',
        days: 'dagen',
        paid: 'Betaald',
        draft: 'Concept',
        sent: 'Verzonden',
        overdue: 'Te laat',
      }),
      primaryColor: '#4f46e5',
      secondaryColor: '#1f2937',
      accentColor: '#10b981',
      fontFamily: 'Helvetica',
      borderRadius: '16px',
      showLogo: true,
      showPaymentInfo: true,
      showNotes: true,
      showTerms: true,
      showImpactBadge: true,
      paymentTerms: 'Betaling binnen 30 dagen',
      showSocialImpact: true,
      pageSize: 'A4',
      orientation: 'portrait',
      margins: '{"top":60,"right":60,"bottom":60,"left":60}',
    },
  })

  // Create default English template (for international freelancers)
  const enTemplate = await prisma.invoiceTemplate.upsert({
    where: { id: 'default-en' },
    update: {},
    create: {
      id: 'default-en',
      name: 'Professional English',
      description: 'Standard English professional invoice',
      language: 'en',
      currency: 'EUR',
      currencySymbol: '€',
      currencyPosition: 'before',
      isDefault: false,
      labels: JSON.stringify({
        invoice: 'INVOICE',
        invoiceNumber: 'Invoice Number',
        date: 'Invoice Date',
        dueDate: 'Due Date',
        description: 'Description',
        quantity: 'Quantity',
        unitPrice: 'Unit Price',
        amount: 'Amount',
        subtotal: 'Subtotal',
        tax: 'VAT',
        total: 'Total',
        paymentInfo: 'Payment Information',
        paymentTerms: 'Payment Terms',
        bankAccount: 'Bank Account',
        iban: 'IBAN',
        bic: 'BIC',
        vatNumber: 'VAT Number',
        from: 'From',
        to: 'To',
        thankYou: 'Thank you for your business!',
        dueIn: 'Due in',
        days: 'days',
        paid: 'Paid',
        draft: 'Draft',
        sent: 'Sent',
        overdue: 'Overdue',
      }),
      primaryColor: '#4f46e5',
      secondaryColor: '#1f2937',
      accentColor: '#10b981',
      fontFamily: 'Helvetica',
      borderRadius: '16px',
      showLogo: true,
      showPaymentInfo: true,
      showNotes: true,
      showTerms: true,
      showImpactBadge: true,
      paymentTerms: 'Net 30',
      showSocialImpact: true,
      pageSize: 'A4',
      orientation: 'portrait',
      margins: '{"top":60,"right":60,"bottom":60,"left":60}',
    },
  })

  // Create default German template (for cross-border NL-DE freelancers)
  const deTemplate = await prisma.invoiceTemplate.upsert({
    where: { id: 'default-de' },
    update: {},
    create: {
      id: 'default-de',
      name: 'Professionell Deutsch',
      description: 'Standard deutsche professionelle Rechnung',
      language: 'de',
      currency: 'EUR',
      currencySymbol: '€',
      currencyPosition: 'before',
      isDefault: false,
      labels: JSON.stringify({
        invoice: 'RECHNUNG',
        invoiceNumber: 'Rechnungsnummer',
        date: 'Rechnungsdatum',
        dueDate: 'Fälligkeitsdatum',
        description: 'Beschreibung',
        quantity: 'Menge',
        unitPrice: 'Einzelpreis',
        amount: 'Betrag',
        subtotal: 'Zwischensumme',
        tax: 'MwSt.',
        total: 'Gesamt',
        paymentInfo: 'Zahlungsinformationen',
        paymentTerms: 'Zahlungsbedingungen',
        bankAccount: 'Bankkonto',
        iban: 'IBAN',
        bic: 'BIC',
        vatNumber: 'USt-IdNr.',
        from: 'Von',
        to: 'An',
        thankYou: 'Vielen Dank für Ihren Auftrag!',
        dueIn: 'Fällig in',
        days: 'Tagen',
        paid: 'Bezahlt',
        draft: 'Entwurf',
        sent: 'Gesendet',
        overdue: 'Überfällig',
      }),
      primaryColor: '#4f46e5',
      secondaryColor: '#1f2937',
      accentColor: '#10b981',
      fontFamily: 'Helvetica',
      borderRadius: '16px',
      showLogo: true,
      showPaymentInfo: true,
      showNotes: true,
      showTerms: true,
      showImpactBadge: true,
      paymentTerms: 'Zahlbar innerhalb 30 Tagen',
      showSocialImpact: true,
      pageSize: 'A4',
      orientation: 'portrait',
      margins: '{"top":60,"right":60,"bottom":60,"left":60}',
    },
  })

  console.log('Seeded templates:', nlTemplate.name, enTemplate.name, deTemplate.name)
  console.log('Done! FreeInvoice is ready for Dutch freelancers.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
